-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- 1.List the number of films per category.
USE sakila;

SELECT c.name, COUNT(*) 
FROM film_category AS fc
INNER JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name;

-- 2.Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, co.country
FROM address AS a
INNER JOIN store as s
ON a.address_id = s.address_id
INNER JOIN city as c
ON a.city_id=c.city_id
INNER JOIN country as co
ON c.country_id = co.country_id;

-- 3.Calculate the total revenue generated by each store in dollars.
SELECT i.store_id, SUM(f.rental_rate) AS total_revenue
FROM film AS f
INNER JOIN inventory AS i
ON f.film_id = i.film_id
GROUP BY i.store_id;

-- 4.Determine the average running time of films for each category.

SELECT c.name, AVG(f.length)
FROM film AS f
INNER JOIN film_category AS fc
ON f.film_id = fc.film_id
INNER JOIN category AS c
ON fc.category_id= c.category_id
GROUP BY c.name;


